name: Replace whitevideo field in JSON

on:
  schedule:
    - cron: '0 16 * * *' # 每天0点（UTC时间16点）执行

jobs:
  replace-whitevideo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch JSON
        run: |
          curl https://api.yjllq.com/index.php/api/settle/settlev11 -o settle.json

      - name: Replace whitevideo field
        run: |
          sed -i 's/"whitevideo": \[.*\]/"whitevideo": []/' settle.json

      - name: Commit and push
        run: |
          git add settle.json
          git commit -m "Automatically update whitevideo field in settle.json"
          git push
