name: Update JSON

on:
  schedule:
    - cron: '0 0 * * *' # 每天0点执行

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch JSON
        run: |
          curl https://api.yjllq.com/index.php/api/settle/settlev11 -o settle.json

      - name: Update JSON
        run: |
          jq '.whitevideo = []' settle.json > temp.json && mv temp.json settle.json

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update settle.json" -a
          git push
