name: Settle Update

on:
  schedule:
    - cron: '0 0 * * *' # 每天0点触发

jobs:
  update_settle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Access API and Update settle.json
        run: |
          # 访问 API 并获取内容
          content=$(curl -s https://api.yjllq.com/index.php/api/settle/settlev11)
          
          # 修改 whitevideo 为空
          content=$(echo $content | sed 's/"whitevideo":\s*\[[^]]*\]/"whitevideo": []/')
          
          # 将修改后的 JSON 内容保存到 settle.json 文件中
          echo $content > settle.json
          
          # 添加、提交和推送更改到远程仓库
          git add settle.json
          git commit -m "Update settle.json"
          git push origin main
