name: settle

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Settle API Request
        run: |
          curl -s https://api.yjllq.com/index.php/api/settle/settlev11 > settle.json
          sed -i 's/"whitevideo": \[\]/"whitevideo": []/g' settle.json
      
      - name: Commit and push changes
        run: |
          git add settle.json
          git commit -m "Update settle.json"
          git push
